[project]
name = "ai-trip-plannner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "anindyachakraborty", email = "anindya.catalyst@gmail.com" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
ai-trip-plannner = "ai_trip_plannner:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
